spring.application.name=MobileAppBackend
server.address=0.0.0.0
jwt.secret=s3cr3tK3yForJWTGenerationWhichIsLongEnough123!
spring.mongodb.uri=mongodb+srv://kuraken:Oo7qWe1z0IUudv9I@cooking-app.apze1bz.mongodb.net/mydatabase?retryWrites=true&w=majority
spring.mongodb.database=mydatabase