/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/recipes/create-recipe`; params?: Router.UnknownInputParams; } | { pathname: `/recipes/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/recipes/create-recipe`; params?: Router.UnknownOutputParams; } | { pathname: `/recipes/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/recipes/create-recipe${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/recipes/create-recipe`; params?: Router.UnknownInputParams; } | `/recipes/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/recipes/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
